### ISSUE TITLE
Does Hyperenclave have its own remote attestation design?

### ISSUE THREAD

**Issue by Ariel08081214** [asterinas/hyperenclave#15]
Hai. 
I noticed that users can test the remote attestation with Occlum. The flows of remote attestation are different. 
Does Hyperenclave have its own remote attestation design? 
Does Hyperenclave need to rely on a third-party attestation center？
Does Hyperenclave has a Quoting Enclave and a Remote Key Exchange (KE) Libraries like Intel SGX？

**Comment by Ariel08081214** [comment]
> Hai. I noticed that users can test the remote attestation with Occlum. The flows of remote attestation are different. Does Hyperenclave have its own remote attestation design? Does Hyperenclave need to rely on a third-party attestation center？Does Hyperenclave has a Quoting Enclave like Intel SGX？

**Comment by yilingxu** [comment]
> I noticed that users can test the remote attestation with Occlum. The flows of remote attestation are different.

Are you mentioning this demo https://github.com/asterinas/hyperenclave/tree/master/demos/RemoteAttestation? Yes, we have provided FAKE TPM attestation demo.

> Does Hyperenclave have its own remote attestation design?

Yes. HyperEnclave relies on TPM to provide the ability of measurement and authentication. Details can be found in HyperEnclave's paper.

> Does Hyperenclave need to rely on a third-party attestation center？

Yes. The certificate on HyperEnclave is issued by [CFCA](https://www.cfca.com.cn/), and users can verify the authenticity of the certificate through CFCA.

> Does Hyperenclave has a Quoting Enclave and a Remote Key Exchange (KE) Libraries like Intel SGX？

Hyperenclave does not include a Quoting Enclave, instead, the trusted Hypervisor verify the integrity of Report and convert the Report to the Quote. 

Hyperenclave does not depend on Remote Key Exchange (KE) Libraries, instead, Hyperenclave depends on TPM-derived keys.

**Comment by Ariel08081214** [comment]
> Are you mentioning this demo https://github.com/asterinas/hyperenclave/tree/master/demos/RemoteAttestation? Yes, we have provided FAKE TPM attestation demo.

No, I mean Occlum support five kinds of remote_attestation ways. If the application runs with Occlum，does it means that the application do not need care about remote attestation coding or configuration？
![image](https://github.com/user-attachments/assets/6766262f-68a1-4c34-91a2-4c85965d7d65)

> Yes. The certificate on HyperEnclave is issued by [CFCA](https://www.cfca.com.cn/), and users can verify the authenticity of the certificate through CFCA.

Then who is the `users`? Do users need to do some configuration work for connecting CFCA?  

Users verify the authenticity of the certificate through CFCA means that Hyperenclave is a real and secure TEE，right？

>Hyperenclave does not include a Quoting Enclave, instead, the trusted Hypervisor verify the integrity of Report and convert the Report to the Quote.

Does the trusted Hypervisor means RustMonitor? Does Hyperenclave(RustMonitor) charges the generation of Report?  Who verifies the Report or Quote? Is CFCA?

Here are the HyperEnclave's paper's descriptions: <br>The enclave measurement is signed using `RustMonitor’s attestation key` to form the enclave measurement signature (ems). The TPM quote TMP_Quote,which is signed using `the TPM attestation key`, includes thePCRs for the measurement of all booted code, and the measurement of hapk.
It seems that there are two kinds of attestation keys for remote attestation flow,right?

**Comment by yilingxu** [comment]
Hi @Ariel08081214

**Comment by yilingxu** [comment]
Hi @Ariel08081214 

> If the application runs with Occlum，does it means that the application do not need care about remote attestation coding or configuration？

Application runs with Occlum need to care about remote attestation. More ablout Occlum remote attestation, You may dive deeply into Occlum's source code or discuss it in Occlum's community: https://github.com/occlum/occlum.

> Then who is the users? Do users need to do some configuration work for connecting CFCA?

There is a tool on HyperEnclave for connecting CFCA to apply certificate, but its source code is not open-sourced now. Instead, we have provided FAKE TPM attestation demo, which dose not rely on a third-party: https://github.com/asterinas/hyperenclave/tree/master/demos/RemoteAttestation.

> Users verify the authenticity of the certificate through CFCA means that Hyperenclave is a real and secure TEE，right？

Yes.


> Does the trusted Hypervisor means RustMonitor? 

Yes.

> Does Hyperenclave(RustMonitor) charges the generation of Report? Who verifies the Report or Quote? Is CFCA?


The RustMonitor verifies the Report and convert the Report to the Quote. 
The Remote User verifies the Quote, as well as verifying the certificate chain(up to the root CFCA Certificate) for generating the signature in Quote.


> Here are the HyperEnclave's paper's descriptions:
The enclave measurement is signed using RustMonitor’s attestation key to form the enclave measurement signature (ems). The TPM quote TMP_Quote, which is signed using the TPM attestation key, includes thePCRs for the measurement of all booted code, and the measurement of hapk.
It seems that there are two kinds of attestation keys for remote attestation flow,right?

Yes.

**Comment by Ariel08081214** [comment]
Hai @yilingxu

> The Remote User verifies the Quote, as well as verifying the certificate chain(up to the root CFCA Certificate) for generating the signature in Quote.

Does the remote user need to connect CFCA to verify the certificate? 

Does the remote user need to send a nonce to TPM for getting the Quote?

**Comment by yilingxu** [comment]
Hi @Ariel08081214

> Does the remote user need to connect CFCA to verify the certificate?

The remote user only need to get root CFCA Certificate, by offline or online.

> Does the remote user need to send a nonce to TPM for getting the Quote?

There is a `report_data` field in Report, which will be included in Quote, you can put a nonce at `report_data` field.

**Comment by Ariel08081214** [comment]
Hai @yilingxu
Thanks for your timely reply.
As the paper's statments about Remote Attestation:
1. After RustMonitor is booted, it needs to extend the trust to the enclaves. For this purpose, RustMonitor derives an attestation key pair which is used to sign the enclave measurement.Then RustMonitor extends the derived public key to the TPM PCR, and the private key never leaves RustMonitor which is protected by memory isolation and encryption.

How does the enclave measurement been signed with the RustMonitor’s attestation key when the private key never leaves RustMonitor?

What kind of certificate does the Hyperenclave(TPM) get form CFCA to sign the Quote? Is the AIK certificate or EK certificate?

2. With the measured late launch, all booted components are measured and extended to the TPM. After RustMonitor is booted, it needs to extend the trust to the enclaves. For this purpose, RustMonitor derives an attestation key pair which is used to sign the enclave measurement.

Where does the RustMonitor derive attestation key pair form？

**Comment by yilingxu** [comment]
Hi @Ariel08081214

> How does the enclave measurement been signed with the RustMonitor’s attestation key when the private key never leaves RustMonitor?

The enclave measurement is stored in RustMonitor’s memory, and signed with the RustMonitor’s attestation key.

> What kind of certificate does the Hyperenclave(TPM) get form CFCA to sign the Quote? Is the AIK certificate or EK certificate?

The AIK certificate.

> Where does the RustMonitor derive attestation key pair from？

The RustMonitor’s attestation key are derived from a root key from the random number generator (RNG) module of the TPM. Details can be found in HyperEnclave's paper.
