### ISSUE TITLE
Some confusions regarding The HyperEnclave quote structure

### ISSUE THREAD

**Issue by Ariel08081214** [asterinas/hyperenclave#19]
The paper's Figure 4 shows the HyperEnclave quote structure as follows
![image](https://github.com/user-attachments/assets/907936a4-1f39-4928-b568-f3aa1126e44c)

It seems that the HyperEnclave quote consist of four parts，ems、hapk、TPM_Quote、TPM_AK_Cert，is that right?
Can you explain the TPM_Quote and TPM_AK_Cert in detail?  Looking forward to your reply. Thank you very much.

**Comment by yilingxu** [comment]
Hi @Ariel08081214

> It seems that the HyperEnclave quote consist of four parts，ems、hapk、TPM_Quote、TPM_AK_Cert，is that right?

Yes.

> Can you explain the TPM_Quote and TPM_AK_Cert in detail? 

The TPM_Quote and TPM_AK_Cert are following TCG, you may dive deeply into TCG spec: https://trustedcomputinggroup.org/resource/tpm-library-specification/.

**Comment by Ariel08081214** [comment]
Hai @yilingxu
> The TPM_Quote and TPM_AK_Cert are following TCG, you may dive deeply into TCG spec: > https://trustedcomputinggroup.org/resource/tpm-library-specification/.

Well, TPM's integrity can be verified through TPM_Quote and TPM_AK_Cert.  But I wonder how to use the ems and hapk for remote attestation. That is not covered in the Paper.

**Comment by yilingxu** [comment]
Hi @Ariel08081214

The TMP_Quote, which includes the PCRs for the measurement of all booted code and the mesurement of hapk, is verified through TPM_AK_Cert. The ems is verified through hapk.

**Comment by Ariel08081214** [comment]
Hai. @yilingxu
> The ems is verified through hapk.

TPM_AK_Cert can be certified by CFCA,but how to ensure the truthfulness of the hapk? 
If the TMP_Quote include the ems, Why the ems still need to be verified by hapk?

**Comment by yilingxu** [comment]
Hi @Ariel08081214

> TPM_AK_Cert can be certified by CFCA, but how to ensure the truthfulness of the hapk?

The hapk is verified by PCR13(the measurement of hapk) in TMP_Quote, and the TMP_Quote is verified by TPM_AK_Cert, and the TPM_AK_Cert can be certified by CFCA.

> If the TMP_Quote include the ems, Why the ems still need to be verified by hapk?

The TMP_Quote does not contain ems. The TMP_Quote contains the measurement of booted code (including the CRTM, BIOS, grub, kernel, initramfs, and hypervisor).
