### ISSUE TITLE
[QUESTION] About uninstalling hyperenclave

### ISSUE THREAD

**Issue by pyz-creeper** [asterinas/hyperenclave#27]
### Your Question

Is there a way to uninstall hyperenclave after I finish my experiements?

### Relevant Documentation or Forum Link 

Hyperenclave paper: https://www.usenix.org/conference/atc22/presentation/jia-yuekai.

### Additional context

I think hyperenclave start up a os which runs on hypervisor mode. I wonder if I install it on my server to conduct some experiements, how should I recover my server once I finish it? What's more, I want to know if such recover method exists, is it still secure to use hyperenclave?

**Comment by Bonjourz** [comment]
Hi @pyz-creeper , HyperEnclave can be uninstalled. Before HyperEnclave is uninstalled, HyperEnclave will scrub all the secret in memory and hardware registers.

> I wonder if I install it on my server to conduct some experiements, how should I recover my server once I finish it?

For open-sourced HyperEnclave, currently we do not provide scripts for disabling HyperEnclave. If you want to recovery your server, just reboot your machine and reset your environment.

> I want to know if such recover method exists, is it still secure to use hyperenclave?

In production environment, all the operations are recorded in PCR registers in TPM. So any attempts to forge HyperEnclave environment will be reflected to the PCR registers in TPM, and user is able to verify that during Remote Attestation.

**Comment by pyz-creeper** [comment]
Thanks for the quick response @Bonjourz. I think this answer solves my problem.
