### ISSUE TITLE
Installation failed on cloud service.

### ISSUE THREAD

**Issue by pyz-creeper** [asterinas/hyperenclave#29]
Hi,
I am using Aliyun cloud service to install environment for HyperEnclave. I followed the installation guide step by step, from reinstalling the kernel to 5.10.0, to the last step starting the service. I ran dmesg and got the following result:

command: ~/hyperenclave/scripts# dmesg | grep hyper

[   91.378659] hyper_enclave: loading out-of-tree module taints kernel.
[   91.378717] hyper_enclave: module verification failed: signature and/or required key missing - tainting kernel
[  254.543904] Modules linked in: iptable_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c xt_addrtype iptable_filter bpfilter br_netfilter bridge stp llc overlay hyper_enclave(OE) intel_rapl_msr intel_rapl_common intel_powerclamp nls_iso8859_1 crct10dif_pclmul ghash_clmulni_intel cirrus aesni_intel crypto_simd drm_kms_helper cryptd cec glue_helper rapl rc_core fb_sys_fops syscopyarea input_leds sysfillrect sysimgblt serio_raw pvpanic qemu_fw_cfg mac_hid sch_fq_codel drm ramoops reed_solomon pstore_blk pstore_zone efi_pstore ip_tables x_tables autofs4 nvme_tcp nvme_rdma rdma_cm iw_cm ib_cm ib_core nvme_fc nvme_fabrics virtio_net nvme net_failover i2c_piix4 crc32_pclmul failover psmouse nvme_core floppy [last unloaded: hyper_enclave]

the boot_image macro in dmesg is this (not sure if this is right?):
Command line: BOOT_IMAGE=/boot/vmlinuz-5.10.0-051000-generic root=UUID=05b5f359-2108-4208-9ecd-8eff3357a7cb ro vga=792 console=tty0 console=ttyS0,115200n8 net.ifnames=0 noibrs iommu=pt nvme_core.io_timeout=4294967295 nvme_core.admin_timeout=4294967295 memmap=8G$0x100000000 iommu=off intremap=off no5lvl quiet

I can not understand why this happens? I guess it might be related to the fact that I was using a cloud service, which may have a very different boot up measurement for TPM. I wonder if you authors have tried installing it on commercial cloud service before?

**Comment by Bonjourz** [comment]
Hi @pyz-creeper , thanks for your interest on HyperEnclave.

The message shown in the log you provide:

> [ 91.378717] hyper_enclave: module verification failed: signature and/or required key missing - tainting kernel

indicates that the OS vendor has enabled the [kernel module signature verification](https://www.kernel.org/doc/html/v5.1/admin-guide/module-signing.html) on your kernel, and it won't load any module that hasn't been singed.

>  I wonder if you authors have tried installing it on commercial cloud service before?

We are now working on deploying HyperEnclave in virtualized environment.

For now, suggest do not try HyperEnclave on cloud environment. Currently HyperEnclave needs to be deployed on bare-mental hardware. You can try it on your the PC or server.

**Comment by pyz-creeper** [comment]
Thank you @Bonjourz . I will follow your suggestions and run my experiment on a local PC.
