### ISSUE TITLE
Which mode is occlum in？Is it secure mode？

### ISSUE THREAD

**Issue by Ariel08081214** [asterinas/hyperenclave#4]
Hai
If the application runs in hyperenclave with occlum，Which mode is occlum and application in？Is it secure mode？

**Comment by Bonjourz** [comment]
Hi @Ariel08081214 ，Occlum and application run in the TEE environment which is provided by HyperEnclave. 

We do not have a specific name to describe such mode. You can understand that Occlum and application is secured by HyperEnclave.
