### ISSUE TITLE
failed to build the HyperEnclave's driver

### ISSUE THREAD

**Issue by walkovernamtso** [asterinas/hyperenclave#5]
$ cd hyperenclave-driver
$ make

error messges as follows, how to fix?

sunqihao@zhi:/opt/hyperenclave-driver$ make
make -C /lib/modules/`uname -r`/build M=/opt/hyperenclave-driver modules
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  You are using:           gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
  UPD     /opt/hyperenclave-driver/include/generated/version.h
  CC [M]  /opt/hyperenclave-driver/driver/edmm.o
In file included from /opt/hyperenclave-driver/driver/enclave.h:16,
                 from /opt/hyperenclave-driver/driver/edmm.c:14:
/opt/hyperenclave-driver/driver/main.h:36:15: error: ‘printk_safe_flush’ undeclared here (not in a function); did you mean ‘printk_trigger_flush’?
   36 | extern typeof(printk_safe_flush) *printk_safe_flush_sym;
      |               ^~~~~~~~~~~~~~~~~
      |               printk_trigger_flush
/opt/hyperenclave-driver/driver/main.h:40:15: error: ‘flush_tlb_kernel_range’ undeclared here (not in a function)
   40 | extern typeof(flush_tlb_kernel_range) *flush_tlb_kernel_range_sym;
      |               ^~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:297: /opt/hyperenclave-driver/driver/edmm.o] Error 1
make[2]: *** [scripts/Makefile.build:560: /opt/hyperenclave-driver/driver] Error 2
make[1]: *** [Makefile:1906: /opt/hyperenclave-driver] Error 2
make: *** [Makefile:17: modules] Error 2

**Comment by Bonjourz** [comment]
Hi @daydayuphere , could you show the version of your kernel? By typing `uname -r`:

```bash
$ uname -r
```

**Comment by walkovernamtso** [comment]
5.10.134-csv

**Comment by Bonjourz** [comment]
Hi @daydayuphere , HyperEnclave now only support Linux Kernel with version 5.4 and version 4.19, see the description in :https://github.com/asterinas/hyperenclave?tab=readme-ov-file#supported-linux-kernel-version.

Could you change the Linux kernel version to 5.4 on your platform?

**Comment by walkovernamtso** [comment]
Our server's CPU is Hygon, which requires upgrading the OS kernel from 5.4 to 5.10.
https://openanolis.cn/sig/Hygon-Arch/doc/865622272844371792
what should I do if I want to test hyperenclave on hygon platform?

**Comment by Bonjourz** [comment]
Hi @daydayuphere 

For Hygon platform, OS listed here(https://openanolis.cn/sig/Hygon-Arch/doc/1076446632387394260) includes kernel 5.4 and kernel 4.19. Cloud you please use the kernel based on 4.19 or 5.4?

If you need to use Kernel 5.10, please wait for a while. We plan to support Kernel 5.10 for HyperEnclave this year.

**Comment by walkovernamtso** [comment]
3ks，I try it later.

**Comment by 1160300918** [comment]
> Hi @daydayuphere , could you show the version of your kernel? By typing `uname -r`:
> 
> ```shell
> $ uname -r
> ```

Hi, I failed to build the HyperEnclave-driver with hygon CPU, error messages as follows, please help analyzing: 
```shell
$ uname -r
4.19.90-23.42.v2101.ky10.x86_64

$ make
make -C /lib/modules/`uname -r`/build M=/home/asterinas/hyperenclave-driver modules
     UPD /home/asterinas/hyperenclave-driver/include/generated/version.h 
     CC[M]/home/asterinas/hyperenclave-driver/driver/edmm.o 
     CC [M] /home/asterinas/hyperenclave-driver/driver/enclave.o
/home/asterinas/hyperenclave-driver/driver/enclave.c: In function ' he_cmd_encl_add_page’ :
/home/asterinas/hyperenclave-driver/driver/enclave. c:338:70: error: macro "access_ok" passed 3 arguments, but takes just 2 
     if (!access_ok(VERIFY_READ，(void__user *)source_address,PAGE_SIZE)){
/home/asterinas/hyperenclave-driver/driver/enclave. c:338:7: error: ' access_ok’undeclared (first use in this function) 
     if (!access_ok(VERIFY_READ，(void __user *)source_address,PAGE_SIZE)) {
/home/asterinas/hyperenclave-driver/driver/enclave.c:338:7: note: each undeclared identifier is reported only once for each function it appears in 
make[3]:*** [scripts/Makefile.build:304: /home/asterinas/hyperenclave-driver/driver/enclave.o] Error 1 
make[2]: ***[scripts/Makefile.build;544: /home/asterinas/hyperenclave-driver/driver] Error 2 
make[1]: *** [Makefile:1557: _module_/home/asterinas/hyperenclave-driver] Error 2 
make: *** [Makefile;17: modules] Error 2

$ lscpu
Architecture:                              x86_64 
CPU op-mode(s):                      32-bit,64-bit 
Byte Order:                                 Little Endian 
Address sizes:                            43 bits physical, 48 bits virtual 
CPU(s):                                        128 
On-line CPU(s) list:                    0-127 
Thread(s) per core:                    2 
Core(s) per socket:                    32
Socket(s):                                    2
NUMA node(s):                           8
Vendor ID:                                    HygonGenuine 
CPU family:                                 24 
Model:                                          2
Model name:                               Hygon C86 7380 32-core Processor
.............
```
