### ISSUE TITLE
Start HyperEnclave error

### ISSUE THREAD

**Issue by walkovernamtso** [asterinas/hyperenclave#6]
$ cd hyperenclave/scripts
$ bash start_hyperenclave.sh

![image](https://github.com/user-attachments/assets/3ba3d991-a102-4319-b6bd-eba157040dad)

**Comment by Bonjourz** [comment]
Hi @daydayuphere , there exist some issues when building hyperEnclave-driver. Let us solve this issue(https://github.com/asterinas/hyperenclave/issues/5) first.

**Comment by daydayuphere** [comment]
5.10.134-csv

**Comment by walkovernamtso** [comment]
I am conducting hyperenclave verification on two hardware platforms: one is an Intel i5 platform, and the other is a Hygon platform. This issue occurs on the Intel i5 platform.

cpu:  12th Gen Intel(R) Core(TM) i5-1240P   1.70 GHz
VM: created by oracle virtualbox
OS:  ubuntu 20.04

**Comment by Bonjourz** [comment]
Hi @daydayuphere 

Cant you successfully build HyperEnclave Driver by following the instructions described by
https://github.com/asterinas/hyperenclave?tab=readme-ov-file#build-the-hyperenclaves-driver:
```bash
$ cd hyperenclave-driver
$ make
$ cd ..
```

By the way, it seems that you are trying to start HyperEnclave in virtualized environment:
> This issue occurs on the Intel i5 platform.
> 
> // ...
**VM: created by oracle virtualbox**
// ...

Currently, HyperEnclave cannot be started in a virtual machine. Please make sure you start HyperEnclave on a physical machine.

**Comment by walkovernamtso** [comment]
ok, many thanks for your reply
