### ISSUE TITLE
How to start HyperEnclave using ZHAOXIN?

### ISSUE THREAD

**Issue by oceanqdu** [asterinas/hyperenclave#7]
The readme only provides examples of using hyperenclave in Intel chips. Is there a difference in the way hyperenclave is used when using other chips? For example, I hope to use hyperenclave in the ZHAOXIN chip. Does hyperenclave currently only support use in x86 architecture? Is there a plan to adapt to ARM?

**Comment by Bonjourz** [comment]
Hi @oceanqdu ,

To my knowledge, the instruction sets for ZHAOXIN chip is similar to Intel. HyperEnclave can support the following ZHAOXIN chip now:
https://github.com/asterinas/hyperenclave?tab=readme-ov-file#zhaoxin

For other ZHAOXIN chips, I'm not sure whether HyperEnclave can act well under the different hardware features. You can have a try by following the [README.md](https://github.com/asterinas/hyperenclave) on your ZHAOXIN platform.

> Does hyperenclave currently only support use in x86 architecture? Is there a plan to adapt to ARM?

Yes. We are now working on ARM platform, and we plan to support ARM in the future.

**Comment by oceanqdu** [comment]
Thank you for your reply @Bonjourz ，
Does Hyperenclave support using software for memory encryption? Is there a plan to support the use of software for memory encryption?

**Comment by Bonjourz** [comment]
Hi @oceanqdu 

HyperEnclave only relies on the memory encryption provided by hardware(AMD SME, and we plan to support Intel MKTME in the future).

For software memory encryption, I think that is orthogonal to HyperEnclave. Do you have any insights or suggestions for this topics?

**Comment by oceanqdu** [comment]
Hi@Bonjourz ,
In the HyperEnclave paper,I saw " HyperEnclave may consider to apply software approaches [76] to encrypt the isolated memory."
For some chips that do not have memory encryption features, I think this is a great solution.

**Comment by Bonjourz** [comment]
Hi @oceanqdu ,

> For some chips that do not have memory encryption features, I think this is a great solution.

Yes. But before we take a solution, we need to weigh up its pros and cons.

**Comment by oceanqdu** [comment]
ok,thanks for your reply
